name = "bankmen-verifier"
type = "javascript"

[build]
command = "npm install --omit=optional && npm run build"
[build.upload]
dir = "public"

# Only for Pages: remove `main` and `node_compat`
# main = "src/index.js"   <-- REMOVE THIS
# node_compat = true      <-- REMOVE THIS
