name: Deploy Bankmen Verifier Worker

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js 22
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install Wrangler CLI
        run: npm install -g wrangler@latest

      - name: Configure Cloudflare secrets
        run: wrangler login --api-token ${{ secrets.CLOUDFLARE_API_TOKEN }}

      - name: Deploy Worker
        run: wrangler deploy --name bankmen-verifier
        env:
          CF_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          HELIUS_API_KEY: ${{ secrets.HELIUS_API_KEY }}
